package main

import (
	"encoding/json"
	"os/exec"
	"strings"
	"text/template"

	"os"
)

const (
	tmpl = `package kingpin

// This file is autogenerated by "go generate .". Do not modify.

{{range .}}
// {{if .Comment}}{{.Comment}}{{else}}{{.|Name}} accumulates {{.Type}} values into a slice.{{end}}
func (p *parserMixin) {{.|Name}}() (target *[]{{.Type}}) {
	target = new([]{{.Type}})
	p.{{.|Name}}Var(target)
	return
}

func (p *parserMixin) {{.|Name}}Var(target *[]{{.Type}}) {
	p.SetValue(new{{.|Name}}Value(target))
}

type {{.Name|Lower}}sValue []{{.Type}}

func new{{.|Name}}Value(p *[]{{.Type}}) *{{.Name|Lower}}sValue {
	return (*{{.Name|Lower}}sValue)(p)
}

func (s *{{.Name|Lower}}sValue) Set(value string) error {
	var v {{.Type}}
	if err := new{{.Name}}Value(&v).Set(value); err != nil {
		return err
	}
	*s = append(*s, v)
	return nil
}

func (s *{{.Name|Lower}}sValue) String() string {
	out := []string{}
	for _, v := range *s {
		out = append(out, new{{.Name}}Value(&v).String())
	}
	return strings.Join(out, ",")
}

func (s *{{.Name|Lower}}sValue) IsCumulative() bool {
	return true
}


{{end}}
`
)

type Repeated struct {
	Name    string `json:"name"`
	Comment string `json:"comment"`
	Plural  string `json:"plural"`
	Type    string `json:"type"`
}

func fatalIfError(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	r, err := os.Open("repeated.json")
	fatalIfError(err)
	defer r.Close()

	v := []Repeated{}
	err = json.NewDecoder(r).Decode(&v)
	fatalIfError(err)

	t, err := template.New("genrepeated").Funcs(template.FuncMap{
		"Lower": strings.ToLower,
		"Name": func(v *Repeated) string {
			if v.Plural != "" {
				return v.Plural
			}
			return v.Name + "List"
		},
	}).Parse(tmpl)
	fatalIfError(err)

	w, err := os.Create("repeated.go")
	fatalIfError(err)
	defer w.Close()

	err = t.Execute(w, v)
	fatalIfError(err)

	err = exec.Command("goimports", "-w", "repeated.go").Run()
	fatalIfError(err)
}
